config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "/home/about" => "home#about", as: "about"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      user_path(current_user.id)
  end

  def create
    @user = sign_in(user_params)
    user_path(current_user.id)
    flash[:notice] = "Signed in successfully."

    @user = sign_up(user_params)
    user_path(current_user.id)
    flash[:notice] = "Welcome! You have signed up successfully."
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def destroy
    @user = log_out(user_params)
    root_path
    flash[:notice] = "Signed out successfully."
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  def user_params
    params.require(:user).permit(:name, :passpord)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
       render :index
    end

  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    flash[:notice] = "You have updated book successfully."
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id)
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

    def book_params
      params.require(:book).permit(:image, :title, :body, :user_id)
    end

    def is_matching_login_user
      book = Book.find(params[:id])
      user = book.user
      unless user.id == current_user.id
        redirect_to books_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top

  end

  def about
  end

    private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about
  end

    private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id)
       flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction, :id)
    end

    def is_matching_login_user
      user = User.find(params[:id])
      unless user.id == current_user.id
        redirect_to user_path(current_user.id)
      end
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.email == "guest@example.com"
        redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user.html.erb
<script src="https://kit.fontawesome.com/076ca8d248.js" crossorigin="anonymous"></script>
  <div class="col-md-3">
    <h2>User info</h2>

    <table class="table">
      <tbody>
        <%= image_tag user.get_profile_image(100,100) %>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <% if user.email != "guest@example.com" %>
      <div class="row">
        <%= link_to "",edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
      </div>
    <% end %>
    <div class="row">
      <%= link_to  edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    </div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="book_body">Body</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
    <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="book_body">Body</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to "Show", book_path(@book.id) %>  |  <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div class="alert" role="alert">
      <div id="error_explanation">
        <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <%= render 'user', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Body</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <% image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<p>new</p>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <dic class="row">
    <%= render 'user', user: @books.user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <div class="row">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr>
                <td>
                  <%= image_tag 'no_image.jpg' %><br />
                  <%= link_to user_path(@books.user) do %>
                      <%= @books.user.name %>
                  <% end %>
                </td>
                <td><%= link_to book_path(@books.id) do %>
                      <%= @books.title %>
                    <% end %>
                </td>
                <td><%= @books.body %></td>
                <td>
                  <% if @books.user == current_user %>
                    <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %>
                  <% end %>
                </td>
                <td>
                  <% if @books.user == current_user %>
                    <%= link_to "Destroy", book_path(@books.id), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "本当に削除しますか？"} %>
                  <% end %>
                </td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to<i class="fa-solid fa-book"></i>Bookers!!</h1>
        <p>In<i class="fa-solid fa-book"></i>Bookers,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
          </div>
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: 'btn btn-primary btn-sm btn-block mb-3' %>
          </div>
          <div class="row">
             <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert" role="alert">
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <script src="https://kit.fontawesome.com/076ca8d248.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <%= link_to "Bookers", root_path, class: 'navbar-brand' %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-users"></i>Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-book-open"></i>Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
                  <i class="fa-solid fa-right-from-bracket"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-house"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-link"></i>About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-right-to-bracket"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="md-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div class="alert" role="alert">
          <div id="error_explanation">
            <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <%= form_with model: @user, multipart: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="user_profile_image">Image</label>
          <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="user_inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/user', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/user', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <% image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>